language: node_js
sudo: false
cache: npm
matrix:
  include:
  - node_js: '6'
  - node_js: '7'
  - node_js: '8'
  - node_js: '8'
    env: TEST_SUITE=test262
script: >
  if [ "$TEST_SUITE" != "test262" ]; then
    npm test
  else
    npm run test:test262
  fi
